### ISSUE TITLE
Make a release with tarball for linux

### ISSUE THREAD

**Issue by hyviquel** [ompcloud/ompcloud-docker#3]
We need a script `make_release` that would construct a tarball (in other words a compressed tar archive) containing all the files needed for a release of OmpCloud:
- the **clang/llvm** executables and libraries (.so files)
- the **libomptarget** library (.so files)
- the **libhdfs3** library (.so files)

OmpCloud releases should be able to run on any **linux amd64** platforms, so do not use optimization flag for specific architecture. To this end, it might be even better to use the [holy-build-box](http://phusion.github.io/holy-build-box/).
One of the arguments of the releasing script should be the version number, for instance:
`./make_release.sh <version>` produces `ompcloud-<version>-linux-amd64.tar.gz`.

Additionally, the tarball should follow Linux standards:
- Files organized in folders lib, bin, etc.
- One script to easily install the files on the machines  
- Containing README, INSTALL and LICENCE files.
- ....

A very nice bonus would be to automatically tag the git repositories and upload the release tarball on Github using their release API ([More information](https://help.github.com/articles/creating-releases/))

**Comment by laurocruz** [comment]
### First Version
Made the first version, still needs to add the README, INSTALL and LICENCE files.

Seems to be working just fine.

**Comment by hyviquel** [comment]
~~I got an [error](https://gist.github.com/hyviquel/aa12d3d836c965c572dd4f991c334c77) when I run it on my computer. I'm looking at a solution but it take a lot of time to run it each time...~~ (fixed in 1488df2d)

Anyway, I have some comments to improve it:
- At the end, it might be better to use the docker image of the standard ubuntu 16.04 and re-install all the packages at the beginning of the script (make it more portable and less dependent on the docker image I use for the test).
- Couldn't we merge some of the *install* and *release* scripts together to avoid all of this duplicated code? We could even use this script in the Dockerfile, thus avoiding to duplicate the code there as well.
- Maybe we could use a Makefile as a wrapper to run the script. For example, `make` would build the tools for the current linux platform, `make release-linux64 0.1` would build and package it into the docker, `make install` would install it, etc.
- On my computer, libhdfs3 seems to be build with optimizations (SSE). Thus, it probably won't run on older processor that do not have SSE instructions available.

Next time you add a new feature, it might be a good idea you fork the repo and do a pull request to allow me to do a review of your code before merging it into the master branch. I think it could be a nice way to improve the quality of our code 😉
