### ISSUE TITLE
(assembly) deduplicate error during merge

### ISSUE THREAD

**Issue by BuShra-Aboubakr** [ompcloud/ompcloud-docker#6]
Hi, 
I install ompcloud following wiki steps, and all completed smoothly but when trying to compile the provided example "matrix-multiplication", I got a deduplication error during the merging step. 

As I understand, during installation, both "AWS Java SDK" and "jetst3" are installed, and while merging, a conflict detected in the contents of the two jars, as attached error-message shows. I tried to add a script in "build.sbt" file but it seems it's overwritten during compilation. 

Any advice on how to fix this?

Thank you
Buchra

[deduplicate_error.txt](https://github.com/ompcloud/ompcloud/files/3975903/deduplicate_error.txt)

**Comment by BuShra-Aboubakr** [comment]
I think I got the cause of that error ! 
I gave "omptargets" different value than what "clang" target has, which conveniently generates that conflict.

Regards, 
Buchra

**Comment by hyviquel** [comment]
Good you found your problem
